[openai]
api_key = "sk-jr8MleGiI1dNhHdhaWbgVjuAiL82KUz3vy-k9IQtD_T3BlbkFJMeXyhBUj0zP_YWjqbBfxcFCVUFTYc7fxG4nUdeWY4A"

[mysql]
user     = "staging_master"
password = "r3yGr*MNz5GT"
host     = "aurex-production-rds.cgnffqcbuhwp.ap-south-1.rds.amazonaws.com"
port     = 3306
database = "aurex_views"

[nvidia]
api_key = "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"


[gsheets]
type = "service_account"
project_id = "gsheets-project-458606"
private_key_id = "b95247f131d63832f1198742e643467f71adeda1"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2NRIql1pdT7E/\n6lOGW8DqNYOvpwkUMd6KNcPSbsAx/cnM22fUeOCxmyxQHndDdPhPg913MsgujGEx\nyoIz5onTU9zAfOT27TQ17A72qAjU9/LRK70G4vbansyAg7GmdSgQygIkhSoSPJO+\n+pnj4LiW4DdkRvtuWQV4NtNvoh0vkTWaubaKfHZnTXCk5af3EEk7uUNi0HKQNEKU\nExlW75jWbDZCb67HRP8+T6xx0BUWoWL1RFrwJdKANKRzb4iTbmxLVj0cdZfHRe/l\njdrH8HVFUwiiiYrJQKNX33/nyX/gaix/BvUbGicX/XwzKzNCQxqXUz7OP1iiIJPI\nKteUvF6RAgMBAAECggEAC6OYe1rDeZgyff8Xkoq4KCXeuXjZsD3uxaShU4cCVTct\nXb4KtAR8MvAy/JOzod4eEgM+AYQfjDSorUPuvQa+GV8fJ/cab6kPl52yh4BMnyEP\nFFw/RQo4w1aXQOLYtWXAt1DWIfPVMAjJVc7fh3JWjEG6nBfaLg529lrHNxdzlpMM\nAVv6rQ01J1BOpq6IWkc/dC/giyrYxbMCpb9SxNeHCkZvh5zTapAhFQQ6jd9jCA2L\nWxp4JLfMr0kNLo7ZQI9/DBOF+OlsbrFvPIsNPpjo2xhejhASv6YJ8+n669YCne48\nV50UVdGmpsxXZGRJjmNXAYwIMIheI1vx1gAlbHpTeQKBgQDnbpUOkZ3jaiKiV2r+\nI3kRI+8HW/jV3KzqAQEg6YfSnbffHiKISfELLFetYA1gRxrnGTZdEpjiL37rE8It\nmuU++rsoJHHxcXgWXgwuf6vgIhlkabZ74dFtQ0W4LzZqwwdA8zWE7uNnAnOAtfSW\n/OdSABF7sGDZAjRSfamjQDIQGQKBgQDJjMEzLhHvl8I7iqBWeWznZKi/e5vRaRFp\nLSwBHa9T8Vu40c1zVRCl6xK4+g2PiQlrusyhHHhzl9YwhPBlVXRbMkk2nvhHEBPT\nZnuYBFm+XE2i4XxVxZfDZxrVaDYbCtn4uckMYYHx02O8eWssNYbe6P9x63hCYjWE\nWpSvgNIxOQKBgHaU5rMsUaYwv8ZG3H+TVXk+3D79FScfh0nvcdCXWAzG22vrWO5U\nVLnQ4qvnR3NJe7Nl68EMwmFCzNlOqnQLpeL7PeJ3qhp4dXugfMVmjX6ueixFLkeT\nkWdWzOZu6ocRnyncdFPEw6gITX5pvQWQWEZf2pVx7m3C/2Q1FzKatgwhAoGAOTOh\ngY0Juh4wGgX2C5Tau7Ft0yqZxo0zS85uNsLeB8zwYzvoO1thJjXZUnZlct9JtTGG\n8hLKfMQTHiIcuCXQqDFVZhMoE8MUXWMwoKxbbBN2VUv5pb42nFae3wJ8mKAzzMut\nq73gy2lbXRp4uEtYw9sM5KAXuX92AOJUYJsHDMECgYEAy60YV654nYj+y5Wnp5Xg\nsjkAMmaAfdghZ+r54fWLP1x016Pq9HHGobmTDq0zBY+NCJUYiJtMZwJMuzkbquWH\nNlCDPJb3y/Ue+w5ndEcMu3FhTFJgJOOjkRQ8esxFGD/LR5//neiTpefTLXcz5l/7\nhQKQnVUtO3dMFPQWm7+4P6E=\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-service-account@gsheets-project-458606.iam.gserviceaccount.com"
client_id = "110646318712130778162"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-service-account%40gsheets-project-458606.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

